### ISSUE TITLE
Генерация ID в аккаунт-сервисе не потокобезопасна

### ISSUE THREAD

**Issue by oxeg** [otherman16/tp_2014_09_AlexGame#2]
Надо подумать, как можно сделать ее такой

**Comment by oxeg** [comment]
Поговорил с Виталием, т.к. у вас пока не было лекции про многопоточность, он посоветовал рассказать вам про то, как это сделать.
В данном случае нужно использовать переменную типа AtomicLong, у которой инкремент нужно делать методом incrementAndGet() - это потокобезопасно.

**Comment by otherman16** [comment]
Спасибо за объяснение, учтем в дальнейшей работе.
С удалением методов работы с MAP-ми из AccountService генерация уникального ID перестала быть актуальной и востребованной. В связи с этим метод удален, можно ли считать этот вопрос решенным?
