### ISSUE TITLE
Дубликация методов в аккаунт сервисе

### ISSUE THREAD

**Issue by oxeg** [otherman16/tp_2014_09_AlexGame#4]
Непонятно, зачем нужно 2 набора одинаковых методов, один из которых работает с БД, второй - нет

**Comment by otherman16** [comment]
Два варианта методов для принципиально разной работы AccountService были оставлены "прозапас", на случай отказа одной из реализаций. Теперь работа с MAP-ами навсегда сохранена в истории commit-ов, но только лишь в ней.
