### ISSUE TITLE
Убрать ненужные комментарии

### ISSUE THREAD

**Issue by oxeg** [otherman16/tp_2014_09_AlexGame#5]
В идеале код должен быть без комментариев вообще. Они допускаются в очень редких случаях, когда происходит что-то неочевидное, и этого не избежать (надо стараться такие случае не создавать).
Но комментарии типа
 // Регистрация пользователя
public boolean registerUser(UserProfile user, HttpSession session) {

// Logout пользователя
public boolean logoutUser(HttpSession session) {

Совершенно излишни. Если по названию метода непонятно, что он делает - нужно назвать этот метод так, чтобы стало понятно.

**Comment by otherman16** [comment]
DONE
Названия методов говорят сами за себя, комментарии действительно не нужны.
